name: 'SSH Login and Execute Custom Commands'
description: 'SSH login to remote server and run custom commands.'
inputs:
  host:
    description: 'Server IP or domain to connect to'
    required: true
  username:
    description: 'Username for SSH login'
    required: true
  script:
    description: 'Custom script to run on the remote server'
    required: true
  port:
    description: 'Port for SSH connection'
    required: false
    default: '22'
  password:
    description: 'Password for SSH login (optional, if SSH key is not used)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Execute commands via SSH
      shell: bash
      run: |
        if [ -z "${{ inputs.password }}" ]; then
          # If password is not provided, use SSH key
          ssh -v -o StrictHostKeyChecking=no -p ${{ inputs.port }} ${{ inputs.username }}@${{ inputs.host }} << 'ENDSSH'
            ${{ inputs.script }}
          ENDSSH
        else
          # If password is provided, use sshpass for password authentication
          sshpass -p "${{ inputs.password }}" ssh -v -o StrictHostKeyChecking=no -p ${{ inputs.port }} ${{ inputs.username }}@${{ inputs.host }} << 'ENDSSH'
            ${{ inputs.script }}
          ENDSSH
        fi
