name: 'Setup SSH Key'
description: 'Setup SSH private key for github workflow.'
inputs:
  ssh_private_key:
    description: 'Private key for SSH authentication'
    required: true
  host:
    description: 'Host to connect to via SSH'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up SSH key
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_private_key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 22 ${{ inputs.host }} >> ~/.ssh/known_hosts
        sudo apt-get install -y sshpass
